import { Ledger, Transaction } from '@/store/transactionStore';
import * as FileSystem from 'expo-file-system';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

export const generatePDF = async (ledger: Ledger, transactions: Transaction[], currencySymbol: string = '$') => {
  const totalIncome = transactions
    .filter((t) => t.type === 'income')
    .reduce((acc, t) => acc + t.amount, 0);
  const totalExpense = transactions
    .filter((t) => t.type === 'expense')
    .reduce((acc, t) => acc + t.amount, 0);
  const balance = totalIncome - totalExpense;

  const htmlContent = `
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
        <style>
          body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 40px; color: #333; }
          .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 40px; border-bottom: 2px solid #EEE; padding-bottom: 20px; }
          .title { font-size: 28px; font-weight: bold; color: #111; margin: 0; }
          .ledger-info { margin-top: 8px; font-size: 16px; color: #666; }
          .summary-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; margin-bottom: 40px; }
          .summary-card { padding: 15px; border-radius: 8px; background-color: #F9FAFB; border: 1px solid #E5E7EB; }
          .summary-label { font-size: 12px; color: #6B7280; text-transform: uppercase; margin-bottom: 4px; }
          .summary-value { font-size: 20px; font-weight: bold; }
          .income { color: #10B981; }
          .expense { color: #EF4444; }
          table { width: 100%; border-collapse: collapse; }
          th { text-align: left; padding: 12px; border-bottom: 2px solid #EEE; color: #666; font-size: 14px; }
          td { padding: 12px; border-bottom: 1px solid #EEE; font-size: 14px; }
          .type-badge { padding: 4px 8px; border-radius: 4px; font-size: 12px; font-weight: 600; text-transform: uppercase; }
          .footer { margin-top: 60px; text-align: center; color: #999; font-size: 12px; }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <h1 class="title">Account Statement</h1>
            <div class="ledger-info">${ledger.name} Ledger</div>
          </div>
          <div style="text-align: right; color: #666;">
            <div>Date Generated: ${new Date().toLocaleDateString()}</div>
          </div>
        </div>

        <div class="summary-grid">
          <div class="summary-card">
            <div class="summary-label">Total Income</div>
            <div class="summary-value income">${currencySymbol} ${totalIncome.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</div>
          </div>
          <div class="summary-card">
            <div class="summary-label">Total Expenses</div>
            <div class="summary-value expense">${currencySymbol} ${totalExpense.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</div>
          </div>
          <div class="summary-card">
            <div class="summary-label">Net Balance</div>
            <div class="summary-value">${currencySymbol} ${balance.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</div>
          </div>
        </div>

        <table>
          <thead>
            <tr>
              <th>Date</th>
              <th>Category</th>
              <th>Description</th>
              <th style="text-align: right;">Amount</th>
            </tr>
          </thead>
          <tbody>
            ${transactions
      .map(
        (tx) => `
              <tr>
                <td>${tx.date}</td>
                <td>${tx.category}</td>
                <td>${tx.title}</td>
                <td style="text-align: right; font-weight: 600; color: ${tx.type === 'income' ? '#10B981' : '#333'}">
                  ${tx.type === 'income' ? '+' : '-'}${currencySymbol} ${tx.amount.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                </td>
              </tr>
            `
      )
      .join('')}
          </tbody>
        </table>

        <div class="footer">
          Generated by Xpenza • Professional Expense Management
        </div>
      </body>
    </html>
  `;

  try {
    const { uri } = await Print.printToFileAsync({ html: htmlContent });
    await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
  } catch (error) {
    console.error('Error generating PDF:', error);
    throw error;
  }
};

export const generateCSV = async (ledger: Ledger, transactions: Transaction[], currencySymbol: string = '$') => {
  const header = `Date,Category,Description,Type,Amount (${currencySymbol} ),Note\n`;
  const rows = transactions
    .map(
      (tx) =>
        `"${tx.date}","${tx.category}","${tx.title}","${tx.type}",${tx.amount},"${tx.note || ''}"`
    )
    .join('\n');

  const csvContent = header + rows;
  const fileName = `${ledger.name.replace(/\s+/g, '_')}_Report.csv`;
  const fileUri = FileSystem.documentDirectory + fileName;

  try {
    await FileSystem.writeAsStringAsync(fileUri, csvContent, {
      encoding: FileSystem.EncodingType.UTF8,
    });
    await Sharing.shareAsync(fileUri, {
      UTI: 'public.comma-separated-values-text',
      mimeType: 'text/csv',
    });
  } catch (error) {
    console.error('Error generating CSV:', error);
    throw error;
  }
};
